
# Table structure for table `lists`
#

CREATE TABLE `lists` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `state` enum('Active', 'Depreciated', 'Waiting') NOT NULL DEFAULT 'Waiting',
  `ordid` int(11) unsigned NOT NULL DEFAULT '0',
  `domainid` int(11) unsigned NOT NULL DEFAULT '0',
  `identid` int(11) unsigned NOT NULL DEFAULT '0',
  `uid` int(11) unsigned NOT NULL DEFAULT '0',
  `unixname` varchar(64) NOT NULL DEFAULT '',
  `newsgroup` varchar(64) NOT NULL DEFAULT '',
  `title` varchar(128) NOT NULL DEFAULT '',
  `description` varchar(255) NOT NULL DEFAULT '',
  `owner` varchar(196) NOT NULL DEFAULT '',
  `password` varchar(255) NOT NULL DEFAULT '',
  `url` varchar(255) NOT NULL DEFAULT '',
  `email` varchar(196) NOT NULL DEFAULT '',
  `email-admin` varchar(196) NOT NULL DEFAULT '',
  `email-bounces` varchar(196) NOT NULL DEFAULT '',
  `email-confirm` varchar(196) NOT NULL DEFAULT '',
  `email-join` varchar(196) NOT NULL DEFAULT '',
  `email-leave` varchar(196) NOT NULL DEFAULT '',
  `email-owner` varchar(196) NOT NULL DEFAULT '',
  `email-request` varchar(196) NOT NULL DEFAULT '',
  `email-subscribe` varchar(196) NOT NULL DEFAULT '',
  `email-unsubscribe` varchar(196) NOT NULL DEFAULT '',
  `pgpkey-id` int(11) unsigned NOT NULL DEFAULT '0',
  `pgpkey-id-admin` int(11) unsigned NOT NULL DEFAULT '0',
  `pgpkey-id-bounces` int(11) unsigned NOT NULL DEFAULT '0',
  `pgpkey-id-confirm` int(11) unsigned NOT NULL DEFAULT '0',
  `pgpkey-id-join` int(11) unsigned NOT NULL DEFAULT '0',
  `pgpkey-id-leave` int(11) unsigned NOT NULL DEFAULT '0',
  `pgpkey-id-owner` int(11) unsigned NOT NULL DEFAULT '0',
  `pgpkey-id-request` int(11) unsigned NOT NULL DEFAULT '0',
  `pgpkey-id-subscribe` int(11) unsigned NOT NULL DEFAULT '0',
  `pgpkey-id-unsubscribe` int(11) unsigned NOT NULL DEFAULT '0',
  `aliases` int(11) unsigned NOT NULL DEFAULT '0',
  `created` int(11) unsigned NOT NULL DEFAULT '0',
  `approve` int(11) unsigned NOT NULL DEFAULT '0',
  `updated` int(11) unsigned NOT NULL DEFAULT '0',
  `deleted` int(11) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `unixnameuid` (`unixname`,`uid`),
  KEY `domainidordid` (`domainid`,`ordid`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
